vich_uploader:
    db_driver: orm

    mappings:
       images:
           uri_prefix: asset/uploads/images
           upload_destination: '%kernel.project_dir%/public/asset/uploads/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
